In [3]:
import numpy as np

In [4]:
# create an array
arr_2d = np.array([[5, 10, 15],[20,25,30],[35, 40, 45]])

In [5]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

There are two general formats for grabbing elements from two arrays or matrix:
* <b>Single bracket</b> format with the comma
* <b>Double bracket</b> format


In [6]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [7]:
# return the value of row 0 and column 0
arr_2d[0][0]

5

In [8]:
# return the entire row of index 0
arr_2d[0]

array([ 5, 10, 15])

In [10]:
# return the value of row 1 and column 1
arr_2d[1][1]

25

In [11]:
# return the value of row 2 and column 1
arr_2d[2][1]

40

In [12]:
# recommend to using comma single bracket notation
# replace the bracket into comma
arr_2d[2,1]

40

In [13]:
arr_2d[1,2]

30

In [14]:
# similar as
arr_2d[1][2]


30

In [15]:
# grab every row but not including row2
# grab every column from column 1 to end
# grab subsection of subsection
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [16]:
arr_2d[:2]


array([[ 5, 10, 15],
       [20, 25, 30]])

In [18]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [19]:
# conditional selection
arr = np.arange(1, 11)

In [20]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Take this array combine it with comparison operators to get a full boolean out of it

In [23]:
# compare all the value in arr with 5 => return boolean
bool_arr = arr > 5

In [24]:
# get all boolean array
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [25]:
# use the boolean array to index or conditional select elements from original
# return the value True
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [26]:
# pass conditional statement in brackets
arr[arr>5]


array([ 6,  7,  8,  9, 10])

In [27]:
arr[arr<3]

array([1, 2])

In [28]:
arr_2d = np.arange(50).reshape(5, 10)

In [29]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [32]:
arr_2d[1:3, 3:5 ]

array([[13, 14],
       [23, 24]])

In [33]:
arr_2d[3,2]


32

In [34]:
arr_2d[2:,4:7]

array([[24, 25, 26],
       [34, 35, 36],
       [44, 45, 46]])