In [8]:
import numpy as np

In [9]:
my_list = [1, 2, 3, 4, 5]

In [13]:
# Create a new array
np.array([[4,4], [3,5]])

array([[4, 4],
       [3, 5]])

In [14]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [15]:
# Create evenly spaced array with arange
# not including the end number
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# The third parameter is the range between each number
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [18]:
# Create evenly spaced array with linspace
# Third parameter is the numbers in array
# the range between each number = End number/(The numbers in array - 1)
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.linspace(0, 5, 2)


array([0., 5.])

In [21]:
np.linspace(0, 50, 11)

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [23]:
# Create identify matrix
# The array including the 10 lists and each list contains 10 objects
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
# Create matrix "Zeros"
# matrix include 3 lists and each list contains 3 objects 0
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.zeros(3)


array([0., 0., 0.])

In [32]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
# Create matrix "Ones"
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
# Create the random number in the uniform distribution from 0 to 1
np.random.rand(10)

array([0.57411208, 0.11171887, 0.02820233, 0.22892425, 0.32012522,
       0.07209335, 0.87153092, 0.08898752, 0.27066912, 0.40539028])

In [37]:
# Create the random number in the standard distribution from 0 to 1
np.random.randn(10)

array([ 0.96902769,  0.77764685,  0.13575527,  1.563172  ,  1.1067122 ,
       -0.03954282, -0.01857835, -0.81356199, -1.4775911 ,  0.86020755])

In [41]:
# Create the random number from the range
# From 0 to 100 but not including the end number
# The third parameter is the numbers
# The random number could repeat
np.random.randint(0, 10, 19)

array([5, 2, 2, 7, 3, 6, 4, 3, 5, 7, 8, 9, 2, 8, 4, 6, 9, 3, 2])

In [55]:
rdarr = np.random.randint(1, 100, 59)

In [48]:
# using the import
from numpy.random import  randint

In [50]:
randint(1, 100, 10)

array([71, 57, 54, 57, 20, 32, 60,  3, 29, 71])

In [57]:
# Max value
np.max(rdarr)

96

In [58]:
rdarr.max()

96

In [59]:
# Min value
np.min(rdarr)


1

In [61]:
rdarr.min()

1

In [63]:
arr = np.arange(25)

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Indexing and Selection


In [66]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [67]:
# Slide array
arr[:3]

array([0, 1, 2])

In [68]:
# Assign the number into new value
arr[:3] = 100


In [69]:
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [70]:
# Copy the array
arr_copy = arr.copy()

In [72]:
arr_copy

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [73]:
# Change the copy
arr_copy[:3] = 200

In [74]:
# The copy array change
arr_copy

array([200, 200, 200,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [76]:
# The original array not change
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

# Indexing and Selection part 2

In [77]:
# Create array
arr_2d = np.array([[5, 10, 15],[20,25,30],[35, 40, 45]])

In [78]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [79]:
# Select value in matrix
arr_2d[0][0]

5

In [101]:
arr_2d[1][2]

30

In [109]:
arr_2d[1:, 1:]

array([[25, 30],
       [40, 45]])

In [110]:
# Create bool array
bool_array = arr_2d > 5

In [111]:
bool_array

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [124]:
arr_2d > 10

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# Select value from the matrix which return True
# return the value higher than 10
arr_2d[arr_2d>10]

In [112]:
# Create new array
new_array = np.arange(50).reshape(10, 5)


In [113]:
new_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [117]:
new_array[1:2, 3:4]

array([[8]])

In [118]:
new_array[3:4, 1:2]

array([[16]])

In [119]:
new_array[3:5, 1:3]




array([[16, 17],
       [21, 22]])