# Numpy operations
* Array with array
* Array with Scalars
* Universal Array Function


In [7]:
import numpy as np

In [8]:
arr = np.arange(0, 11)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Array with Array


In [10]:
# add two arrays together on elements by elements
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

Array with Scalars
* Scalars mean a single number
* Numpy broadcast that number to every element in the array
* The operation occurs also on an element by element basis

In [13]:
# add 100 to every element of array
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [14]:
arr * 100


array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [17]:
# if invalid caculation make (0/0) -> return nan
# it also create a warning instead of error -> still run
arr / arr

C:\Users\admin\AppData\Local\Temp/ipykernel_17548/3460761170.py:3: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [33]:
# this case return inf
1/arr


C:\Users\admin\AppData\Local\Temp/ipykernel_888/4179695011.py:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [34]:
# array with exponent
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

Universal array
* perform the operation and broadcast across entire array

In [35]:
# perform the sqrt operation with all the value
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [36]:
# The number e, also known as Euler's number, is a mathematical constant approximately equal to 2.71828
# e^(value in arr) -> e^1= 2,718, e^2 = 7.38
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [37]:
np.max(arr)

10

In [38]:
# the same as np.max(arr)
arr.max()

10

In [39]:
# sine (sin)
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [40]:
# logarit
np.log(arr)

C:\Users\admin\AppData\Local\Temp/ipykernel_888/3240114484.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [41]:
test = np.arange(0, 11)

In [42]:
np.exp(test)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])