In [54]:
import numpy as np

In [55]:
arr = np.arange(0, 11)

In [56]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
# pick out one or some of elements of an array
arr[8]


8

In [58]:
arr[1:5]

array([1, 2, 3, 4])

In [59]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [60]:
arr[:6]


array([0, 1, 2, 3, 4, 5])

In [61]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [62]:
# grab everything beyond the fifth position
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [63]:
# Broadcast the value to those first five digits to all 100
arr[0:5] = 100

In [64]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [65]:
# reset arr
arr = np.arange(0, 11)

In [78]:
# not a copy but viewing a link to original array -> avoid  memory issues
# if you change the slice_of_arr -> arr will change too
slice_of_arr = arr[0:6]

In [79]:
# get the array from 0th position to 6th position of arr
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [80]:
slice_of_arr[:]


array([99, 99, 99, 99, 99, 99])

In [81]:
# broadcast the value to all 99
slice_of_arr[:] = 99


In [82]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [83]:
# if call back the arr => change as 6 digits into 99
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [84]:
# create a copy => not effect the orignal list when arr_copy change
arr_copy = arr.copy()

In [85]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [86]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [87]:
# broad cast the value to all 100
arr_copy[:] = 100

In [88]:
# the arr_copy change
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [89]:
# the arr not change due to the copy function
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])