In [2]:
import numpy as np

In [3]:
my_list = [1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
# Get back two dimensions array
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Get array of evenly spaced values # not include the stop value
np.arange(0, 10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# This include 3 parameters start, stop, step
# Range is going to be one of the most useful functions for quickly generating an array using
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0, 11, 2)


array([ 0,  2,  4,  6,  8, 10])

In [12]:
# get one dimensional vector with 3 zeros
np.zeros(3)


array([0., 0., 0.])

In [13]:
# the first number is the number of ROWS
# the second number is the number of COLUMN
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
# 2 ROWS, 3 COLUMNS
np.zeros((2, 3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# similar to np.zeros
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
# get 10 evenly point from 0 to 5
# linspace will take in the third argument as number of points
# linspace will automatically divine the stop value to third parameters to get the array
# for example np.linspace(0,5,11) will get the 5/(11-1) = 0.5, therefore the array shoul evenly spaced value by 0.5
np.linspace(0, 5, 11)


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [18]:
np.linspace(0, 5, 3)

array([0. , 2.5, 5. ])

In [19]:
np.linspace(0, 5, 1)

array([0.])

In [20]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
# identity matrix - two dimensional square matrix meaning number of ROWS=COLUMNS and have a DIAGONAL OF ONES with every thing else is ZERO
# identity matrix must be square
# that why only have a single digit
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
# create an array of the given shape you in
# it's going to populate it with random samples from uniform distribution (evenly distribution) over 0 to 1
np.random.rand(5, 4)


array([[0.10426543, 0.06473142, 0.84473088, 0.04681397],
       [0.93907165, 0.41833826, 0.07682752, 0.47726697],
       [0.47573982, 0.25168253, 0.22945386, 0.6111308 ],
       [0.57710721, 0.64305317, 0.9477587 , 0.55999352],
       [0.91016886, 0.48825439, 0.41398695, 0.67586981]])

In [23]:
np.random.rand(5, 5)  # tuple - 5 x 5 matrix of random number

array([[0.98504478, 0.64888568, 0.05066275, 0.03958285, 0.78604998],
       [0.34566725, 0.85823449, 0.65663609, 0.02013965, 0.14775971],
       [0.87033409, 0.22815669, 0.62871336, 0.26308811, 0.98954515],
       [0.39234421, 0.68111512, 0.86994937, 0.68635155, 0.16508687],
       [0.95298192, 0.63654166, 0.34835579, 0.58432789, 0.0917329 ]])

In [24]:
# create an array of the given shape you in
# it's going to populate it with random samples from standard normal distribution center around 0
np.random.randn(2)

array([-0.08680576, -1.57432968])

In [25]:
# create an array of the given shape you in
# it's going to populate it with random samples from standard normal distribution center around 0
# don't pass a tuple -> just pass in each mention as separate argument
# the set of two brackets is a TWO dimensions matrix as an output
np.random.randn(4, 4)

array([[ 0.3052337 ,  0.38881622,  0.19367092, -1.39220046],
       [-0.01730296, -0.3123763 ,  2.58284302,  0.17680339],
       [ 0.02280441,  1.2840895 ,  1.65785593,  0.16291376],
       [-0.85959484,  1.20282937,  0.67583963,  0.4960255 ]])

In [39]:
# get the random integer from 1 to 100
# the low is inclusive (including) but the high is exclusive (no including)
np.random.randint(1, 100)

36

In [40]:
# get the random integer from 1 to 100
# the low is inclusive (including) but the high is exclusive (no including)
# get a particular numbers based on the THIRD arguments (example: 10)
np.random.randint(1, 100, 10)

array([71, 87, 53, 51, 30, 92,  5, 93, 61, 84])

In [41]:
arr = np.arange(25)


In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
ranarr = np.random.randint(0, 50, 10)

In [46]:
# reshape the array with one array with 25 digit by 5 x 5 array using reshape
# if you want excess the number of digits in original array when reshape => error
# for example arr.reshape(5,10) => need 50 elements => only have 25 elements => error
# the size number of row * column = the number or original array
arr.reshape(5, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
# find the max value of ranarr
ranarr.max()

48

In [33]:
# find the min value of ranarr
ranarr.min()

1

In [44]:
# return the actual datatype in data array
arr.dtype

dtype('int32')

In [47]:
# figure out the shape of the vector
# mention that arr is an array was a one dimensional vector
# not putting the parenthesis -> just call the attribute of it
arr.shape

(5, 5)

In [36]:
# By import the function -> reduce the code
from numpy.random import randint

In [37]:
randint(2, 10)

6